### ISSUE TITLE
move validation for tx types in tx structure as functions

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-research#205]
in SignedTx add function `validate(tx)` which matches the type of `tx.data` included and calls the specific validate function e.g. `TxData.validate(tx.data)`

**Comment by d-velev** [comment]
What I did with the oracles was adding an is_x_tx which checks if the map/structure passed has the fields specific to that transaction type, I did it like that since we have to check structures that have been converted to maps when received from an HTTP request, matching in that case won't work. The changes are present in the oracles PR so if you think that solution works, we can close this when it's merged

**Comment by thepiwo** [comment]
I'd want to move the whole validation code into the transactions structure files
